//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGate.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YGate.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Access Denied benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access denied due to insufficient authorization. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AccessDeniedDueToInsufficientAuthorization_ {
            get {
                return ResourceManager.GetString("AccessDeniedDueToInsufficientAuthorization.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blog benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click log in. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Click_log_in {
            get {
                return ResourceManager.GetString("Click_log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click register! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Click_register {
            get {
                return ResourceManager.GetString("Click_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created Entity Count benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreatedEntityCount {
            get {
                return ResourceManager.GetString("CreatedEntityCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you have an account ? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Do_you_have_an_account {
            get {
                return ResourceManager.GetString("Do_you_have_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you not have an account benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Do_you_not_have_an_account {
            get {
                return ResourceManager.GetString("Do_you_not_have_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entity benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entity Property Count benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EntityPropertyCount {
            get {
                return ResourceManager.GetString("EntityPropertyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Identified Entity Count benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IdentifiedEntityCount {
            get {
                return ResourceManager.GetString("IdentifiedEntityCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading the data. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Loading_the_data {
            get {
                return ResourceManager.GetString("Loading_the_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Management benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Market benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modify benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Entity benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MyEntity {
            get {
                return ResourceManager.GetString("MyEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No data currently available. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NoDataCurrentlyAvailable_ {
            get {
                return ResourceManager.GetString("NoDataCurrentlyAvailable.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Passowrd Retry benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Password_Retry {
            get {
                return ResourceManager.GetString("Password_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please choose one benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PleaseChooseOne {
            get {
                return ResourceManager.GetString("PleaseChooseOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RoadMap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RoadMap {
            get {
                return ResourceManager.GetString("RoadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Showed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Showed {
            get {
                return ResourceManager.GetString("Showed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The exit has been made. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string The_exit_has_been_made {
            get {
                return ResourceManager.GetString("The_exit_has_been_made", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no data at all. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string There_is_no_data_at_all {
            get {
                return ResourceManager.GetString("There_is_no_data_at_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Count benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UserCount {
            get {
                return ResourceManager.GetString("UserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wallet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write your message. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Write_your_message {
            get {
                return ResourceManager.GetString("Write_your_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will be redirected to the main page within {second} seconds. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string You_will_be_redirected_to_the_main_page_within_seconds {
            get {
                return ResourceManager.GetString("You_will_be_redirected_to_the_main_page_within_seconds", resourceCulture);
            }
        }
    }
}
